import { defineConfig } from 'vitepress';
// Generated by `bun run convert` from the upstream toc.en.html order.
// Do not hand-edit; change SIDEBAR_GROUPS in scripts/convert-to-md.ts instead.
import sidebar from './sidebar.generated.json';

export default defineConfig({
  title: 'Debian Live Manual',
  titleTemplate: ':title',
  description: 'The official guide to Debian Live systems — build and customize Debian-based live systems.',
  srcDir: '.',

  head: [
    ['meta', { name: 'google-site-verification', content: 'tDvACm_e_Zv56uBvQ2M53jfhumaA1EjkEwkyJU0Ri9Q' }],
    ['link', { rel: 'icon', type: 'image/x-icon', href: 'https://www.debian.org/favicon.ico' }],
    ['meta', { name: 'theme-color', content: '#d70a53' }],
  ],

  themeConfig: {
    logo: {
      light: 'https://www.debian.org/Pics/debian.png',
      dark: 'https://www.debian.org/Pics/debian.png',
      alt: 'Debian',
    },

    siteTitle: 'Debian Live Manual',

    nav: [
      { text: 'Home', link: '/' },
      { text: 'About', link: '/chapters/about-manual' },
      { text: 'Salsa', link: 'https://salsa.debian.org/live-team/live-manual' },
    ],

    sidebar,

    search: {
      provider: 'local',
    },

    lastUpdated: {
      text: 'Last updated',
      formatOptions: { dateStyle: 'medium' },
    },

    docFooter: {
      prev: 'Previous page',
      next: 'Next page',
    },

    socialLinks: [
      {
        icon: {
          // GitLab tanuki logo (Salsa is a GitLab instance run by Debian)
          svg: '<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M23.955 13.587l-1.342-4.135-2.664-8.189c-.135-.423-.73-.423-.867 0L16.418 9.45H7.582L4.919 1.263c-.135-.423-.73-.423-.867 0L1.387 9.452.045 13.587a.924.924 0 0 0 .331 1.023L12 23.054l11.625-8.443a.92.92 0 0 0 .33-1.024" fill="currentColor"/></svg>',
        },
        link: 'https://salsa.debian.org/live-team/live-manual',
        ariaLabel: 'Salsa (Debian GitLab)',
      },
    ],

    footer: {
      message: 'Debian Live Manual — Released under GPL-3+. Debian is a registered trademark of Software in the Public Interest, Inc.',
      copyright: 'Copyright © 2006–2023 Debian Live Project',
    },
  },

  markdown: {
    lineNumbers: true,
  },

  css: {
    lightAndDarkMode: true,
  },
});
